[package]
name = "parcel"
version = "1.0.2"
edition = "2021"
publish = false

[dependencies]
base64 = { version = "0.21" }
clap = { version = "4.4", features = ["derive", "env"] }
futures-util = { version = "0.3" }
lazy_static = { version = "1.4" }
nanoid = { version = "0.4" }
pbkdf2 = { version = "0.12", features = ["simple"] }
poem = { version = "1.3", features = ["cookie", "csrf", "multipart", "session", "static-files"] }
rand_core = { version = "0.6", features = ["std"] }
rand = { version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio", "time"] }
tera = { version = "1.19" }
thiserror = { version = "1.0" }
time = { version = "0.3", features = ["formatting", "macros", "serde"] }
time-humanize = { version = "0.1" }
tokio = { version = "1.32", features = ["full"] }
toml = { version = "0.8" }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
build-data = { version = "0.1" }
