name: Check

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install the Stable Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        env:
          RUSTUP_PERMIT_COPY_RENAME:
        with:
          toolchain: stable
          components: clippy
          cache: false
      - name: Run Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Run Cypress Tests (release)
        run: npm run ci:release
        env:
          DB: /tmp/cypress.db
      - name: Save Cypress artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
