name: Check

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        node-version: "20.x"
      - name: Install Node Packages
        run: npm install
      - name: Install the Stable Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
