name: Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install the Stable Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
          cache: false
      - name: Run Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Run build before Cypress Tests
        run: cargo build
      - name: Run Cypress Tests (debug)
        run: npm run ci:debug
        env:
          DB: /tmp/cypress.db
      - name: Save Cypress artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
